backbone: deit_tiny_patch16_224
batch_size: 32
device: cuda
distance_metric: cosine
embedding_dim: 512
evaluation_thresholds:
- 0.1
- 0.2
- 0.3
- 0.4
- 0.5
- 0.6
- 0.7
- 0.8
- 0.9
learnable_threshold: true
learning_rate: 0.0001
log_dir: ./logs
non_twin_ratio: 0.00001
num_epochs: 100
num_workers: 4
phase1_epochs: 30
phase2_epochs: 40
phase3_epochs: 30
progressive_training: true
same_person_ratio: 0.001
save_dir: ./checkpoints
save_frequency: 1
top_ratio: 0.35
triplet_loss_weight: 0.1
triplet_margin: 0.3
twin_pairs_ratio: 0.001
twin_triplet_margin: 0.1
use_dynamic_weighting: true
verification_loss_weight: 1.0
verification_margin: 0.0
weight_decay: 0.0001
